--SCRIPT JUST FOR H2 DATABASE: For UnitTesting

--Book
INSERT INTO BOOK (BOOKID, BOOKNAME, ISBN , GENRE, QUANTITY, STATE) VALUES (10, 'The Funniest Book Ever', '735402365', 'Drama', '3', '1');
INSERT INTO BOOK (BOOKID, BOOKNAME, ISBN , GENRE, QUANTITY, STATE) VALUES (11, 'The Greatest Book Ever', '963402369', 'Action', '3', '1');
INSERT INTO BOOK (BOOKID, BOOKNAME, ISBN , GENRE, QUANTITY, STATE) VALUES (12, 'The Happiest Book Ever', '015402366', 'Novel', '3', '1');

--User
INSERT INTO USER (USERID, FIRST_NAME, LAST_NAME) VALUES (7, 'Oswaldo', 'Caseres');
INSERT INTO USER (USERID, FIRST_NAME, LAST_NAME) VALUES (8, 'Beatriz', 'Pinzon');
INSERT INTO USER (USERID, FIRST_NAME, LAST_NAME) VALUES (9, 'Nicolas', 'Mora');

--BorrowedBooks
INSERT INTO BORROWEDBOOKS (BORROWEDBOOKSID, EXPECTEDRETURN_DATE, BORROW_DATE, RENEWAL_QUANTITY, BOOKID, USERID, RETURNED, RETURNED_DATE) VALUES (7, '2021-11-20', '2021-11-10', '0', '7', '4', '1', '2021-11-18');
INSERT INTO BORROWEDBOOKS (BORROWEDBOOKSID, EXPECTEDRETURN_DATE, BORROW_DATE, RENEWAL_QUANTITY, BOOKID, USERID, RETURNED, RETURNED_DATE) VALUES (8, '2021-11-21', '2021-11-11', '0', '3', '3', '1', '2021-11-18');
INSERT INTO BORROWEDBOOKS (BORROWEDBOOKSID, EXPECTEDRETURN_DATE, BORROW_DATE, RENEWAL_QUANTITY, BOOKID, USERID, RETURNED, RETURNED_DATE) VALUES (9, '2021-11-22', '2021-11-12', '0', '5', '2', '1', '2021-11-18');

--ticket
INSERT INTO TICKET(TICKETID, TOTAL, BORROWEDBOOKSID) VALUES (34, '2.5', '1');
INSERT INTO TICKET(TICKETID, TOTAL, BORROWEDBOOKSID) VALUES (35, '2.5', '2');
INSERT INTO TICKET(TICKETID, TOTAL, BORROWEDBOOKSID) VALUES (36, '2.5', '4');

