--SCRIPT JUST FOR H2 DATABASE: LOCAL SPRING PROFILE

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
	BOOKID BIGINT NOT NULL AUTO_INCREMENT,
	BOOKNAME VARCHAR(90) NOT NULL,
	ISBN VARCHAR(45) NOT NULL,
	GENRE VARCHAR(45),
	QUANTITY INT NOT NULL,
	STATE TINYINT NOT NULL,
	PRIMARY KEY (BOOKID)
);


DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
	USERID BIGINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	PRIMARY KEY (USERID)
);


DROP TABLE IF EXISTS BORROWEDBOOKS;
CREATE TABLE BORROWEDBOOKS (
	BORROWEDBOOKSID BIGINT NOT NULL AUTO_INCREMENT,
	EXPECTEDRETURN_DATE DATE NOT NULL,
	BORROW_DATE DATE NOT NULL,
	RENEWAL_QUANTITY INT,
	BOOKID INT NOT NULL,
	USERID INT NOT NULL,
	RETURNED TINYINT NOT NULL,
	RETURNED_DATE DATE NOT NULL,	
	PRIMARY KEY (BORROWEDBOOKSID),
	CONSTRAINT BOOKID  FOREIGN KEY (BOOKID) REFERENCES BOOK (BOOKID),
	CONSTRAINT USERID  FOREIGN KEY (USERID) REFERENCES BOOK (USERID)
);

DROP TABLE IF EXISTS TICKET;
CREATE TABLE TICKET (
	TICKETID BIGINT NOT NULL AUTO_INCREMENT,
	TOTAL DOUBLE NOT NULL,
	BORROWEDBOOKSID INT NOT NULL,	
	PRIMARY KEY (TIKETID),
	CONSTRAINT BORROWEDBOOKSID  FOREIGN KEY (BORROWEDBOOKSID) REFERENCES BORROWEDBOOKS (BORROWEDBOOKSID)
);
